export const todosDefault = [
  {
    id: 1,
    heading: 'Магазин',
    text: 'Купить хлеба и соли',
    importantly: 'Важно',
    completed: true,
    createDate: 1537695933,
  },
  {
    id: 2,
    heading: 'Car',
    text: 'Change the rubber and do balancing',
    importantly: ' ',
    completed: false,
    createDate: 1567331133,
  },
  {
    id: 3,
    heading: 'Квартира',
    text: 'Узнать условия ипотеки',
    importantly: ' ',
    completed: false,
    createDate: 1619862333,
  },
  {
    id: 4,
    heading: 'Апельсин',
    text: 'Загуглить способы нарезки',
    importantly: 'Очень важно',
    completed: false,
    createDate: 1657791933,
  },
  {
    id: 5,
    heading: 'Jogging',
    text: 'Calculate calories spent in a month',
    importantly: 'Очень важно',
    completed: false,
    createDate: 1699955133,
  },
]